### ISSUE TITLE
Please Provide More Description Regarding Deployment with Screen Shots

### ISSUE THREAD

**Issue by hpmindquad** [OfficeDev/microsoft-teams-apps-sharenow#4]
**1 -> Where i can find the Azure Deployment Button**

Fill in the various IDs in the template:

a. Bot client ID: The application (client) ID of the Microsoft Teams bot app

b. Bot client secret: The client secret of the Microsoft Teams bot app

c. App Display Name: Name of bot used throughout application.

d. Manifest Id: This needs to be same as manifest Id provided in manifest.json file inside Manifest folder.

e. Tenant ID: The tenant ID above

**1 -> Which bot client id should i use?
2 -> Which client secret should i use?**

**Comment by abbodh** [comment]
Hi @hpmindquad 

1 - Azure deploy button : the Azure deploy button can be found in Step 2 https://github.com/OfficeDev/microsoft-teams-apps-growyourskills/wiki/Deployment-guide#step-2-deploy-to-your-azure-subscription  

1.a - Bot client id is the same application id registered in Step 1. 
1.b - Bot client secret is the same client secret registered in Step 1. 
1.c - App display name is the friendly name registered in Step 1. Please make sure to use the same name as 'Base resource name' during ARM deployment.
1.d - Manifest id can be kept as default. This is the teams manifest id when you will be creating the teams package. https://github.com/OfficeDev/microsoft-teams-apps-sharenow/blob/master/Manifest/manifest.json#L5 
1.e - Tenant id where Teams environment is set up. You can keep the default value if your Azure subscription and Teams tenant is same.

**Comment by abbodh** [comment]
We have further modified the deployment guide by rearranging few steps and adding screenshots. Feel free to open a new issue if you are still facing any challenges.
